// Build script — concatenate src/plugin/*.js into plugin/code.js
// No module system used: files are plain JS sharing a single scope when concatenated.
import { readFileSync, writeFileSync } from "fs";

const { version } = JSON.parse(readFileSync("package.json", "utf8"));

const files = [
  "plugin-src/utils.js",
  "plugin-src/svg-path-helpers.js",
  "plugin-src/paint-and-effects.js",
  "plugin-src/read-helpers.js",
  "plugin-src/handlers-write.js",
  "plugin-src/handlers-library.js",
  "plugin-src/handlers-read.js",
  "plugin-src/handlers-read-detail.js",
  "plugin-src/handlers-tokens.js",
  "plugin-src/handlers-write-ops.js",
  "plugin-src/main.js",
];

const banner = `// figma-mcp — Figma Plugin main thread v1.2.1
// Handles both WRITE (draw UI) and READ (extract design) operations.
// AUTO-GENERATED by scripts/build-plugin.js — edit plugin-src/*.js instead
// Generated: ${new Date().toISOString()}
`;

const parts = files.map(f => {
  const content = readFileSync(f, "utf8");
  return `\n// ── ${f} ──\n${content}`;
});

const output = (banner + parts.join("\n")).replace(/\{\{PLUGIN_VERSION\}\}/g, version);
writeFileSync("plugin/code.js", output);
console.log(`✓ plugin/code.js written (${output.length} chars, ${output.split("\n").length} lines)`);
