// Build script — concatenate plugin-src/*.js into plugin-runtime/code.js
// No module system used: files are plain JS sharing a single scope when concatenated.
import { readFileSync, writeFileSync } from "fs";

const { version } = JSON.parse(readFileSync("package.json", "utf8"));
const cargoVersion = readFileSync("Cargo.toml", "utf8").match(/^version\s*=\s*"([^"]+)"/m)?.[1];
if (version !== cargoVersion) throw new Error(`Version mismatch: package.json ${version}, Cargo.toml ${cargoVersion}`);
if (process.env.GITHUB_REF_TYPE === "tag" && process.env.GITHUB_REF_NAME !== `v${version}`) {
  throw new Error(`Release tag ${process.env.GITHUB_REF_NAME} does not match build version v${version}`);
}

const files = [
  "plugin-src/utils.js",
  "plugin-src/svg-path-helpers.js",
  "plugin-src/paint-and-effects.js",
  "plugin-src/token-helpers.js",
  "plugin-src/read-helpers.js",
  "plugin-src/handlers-write.js",
  "plugin-src/handlers-library.js",
  "plugin-src/handlers-read.js",
  "plugin-src/handlers-read-detail.js",
  "plugin-src/handlers-tokens.js",
  "plugin-src/handlers-write-ops.js",
  "plugin-src/task-scope.js",
  "plugin-src/main.js",
];

const banner = `// figma-mcp — Figma Plugin main thread v${version}
// Handles both WRITE (draw UI) and READ (extract design) operations.
// AUTO-GENERATED by scripts/build-plugin.js — edit plugin-src/*.js instead
`;

const parts = files.map(f => {
  const content = readFileSync(f, "utf8");
  return `\n// ── ${f} ──\n${content}`;
});

const output = (banner + parts.join("\n")).replace(/\{\{PLUGIN_VERSION\}\}/g, version);

const uiPath = "plugin-runtime/ui.html";
const ui = readFileSync(uiPath, "utf8").replace(/(<span class="brand-ver"[^>]*>)[^<]*(<\/span>)/,
  `$1v${version}$2`);
if (!ui.includes(`id="runtime-version">v${version}</span>`)) throw new Error("Missing runtime version badge");
if (process.argv.includes('--check')) {
  if (readFileSync("plugin-runtime/code.js", "utf8") !== output || readFileSync(uiPath, "utf8") !== ui) {
    throw new Error("Plugin bundle is stale; run npm run build:plugin");
  }
} else {
  writeFileSync("plugin-runtime/code.js", output);
  writeFileSync(uiPath, ui);
}
console.log(`✓ plugin-runtime/code.js written (${output.length} chars, ${output.split("\n").length} lines)`);
